### ISSUE TITLE
Extension vs. Accessory?

### ISSUE THREAD

**Issue by adrienne** [paramoredigital/Disable-Template-Editor#2]
Note that since as far as i can tell all this does is inject some CSS and JS into the control panel, it's probably better to remake it as an accessory. Accessories have lower overhead. I may refactor it myself, actually...

**Comment by adrienne** [comment]
Okay, in fact I just did it. (Took about 10 minutes. :)  ) I don't want to submit a pull req, since it's so different -- but you can see it in the branch at: https://github.com/adrienne/Disable-Template-Editor/tree/accessory-refactor

**Comment by struiling** [comment]
I'm sure this would be more complicated, but any chance of making this configurable by member group? Not quite in keeping with the source control motivations, but something that would be useful for a project I have right now.

**Comment by bunchjesse** [comment]
@struiling If you needed that kind of control. You should probably disabled template access in the user's member group preferences.

**Comment by bunchjesse** [comment]
Thanks @adrienne. You're right, this should be an accessory. I'll update it at some point, though, it's not a very high priority for me ATM.

**Comment by adrienne** [comment]
Jesse -- I've actually already redone it as an accessory, if you want me to send a pull request?

**Comment by bunchjesse** [comment]
Yes, please!

**Comment by bunchjesse** [comment]
One thing though, be sure you're using the latest version. v1.0.1 was released tonight. Thanks again.
