### ISSUE TITLE
Hide's the Create New Channel Field Group form

### ISSUE THREAD

**Issue by cuebit** [paramoredigital/Disable-Template-Editor#3]
When this extension is **Enabled**, it's not possible to create a new Channel Field Group, the form is hidden.

Expression Engine: 2.4.0
Add-on version: 1.0.1
Other third party: None

**Comment by bunchjesse** [comment]
Cue, I'm closing this as I've merged your pull request. Thanks again for submitting that fix.

**Comment by cuebit** [comment]
Thanks a 'bunch'
